name: Publish Packages

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build packages
        run: |
          cd shared && pnpm build && cd ..
          cd client && pnpm build && cd ..
          
      - name: Update package configurations for publishing
        run: |
          # Transform shared package
          node -e "
            const pkg = require('./shared/package.json');
            pkg.name = '@martinbechard/wslog-shared';
            require('fs').writeFileSync('./shared/package.json', JSON.stringify(pkg, null, 2));
          "
          
          # Transform client package and dependencies
          node -e "
            const pkg = require('./client/package.json');
            pkg.name = '@martinbechard/wslog-client';
            delete pkg.dependencies['@wslog/shared'];
            pkg.dependencies['@martinbechard/wslog-shared'] = '^1.0.0';
            require('fs').writeFileSync('./client/package.json', JSON.stringify(pkg, null, 2));
          "
          
      - name: Update compiled imports
        run: |
          # Replace imports in compiled JavaScript and TypeScript definitions
          find client/dist -name "*.js" -type f -exec sed -i "s/'@wslog\/shared'/'@martinbechard\/wslog-shared'/g" {} \;
          find client/dist -name "*.d.ts" -type f -exec sed -i "s/'@wslog\/shared'/'@martinbechard\/wslog-shared'/g" {} \;
          find client/dist -name "*.js" -type f -exec sed -i 's/"@wslog\/shared"/"@martinbechard\/wslog-shared"/g' {} \;
          find client/dist -name "*.d.ts" -type f -exec sed -i 's/"@wslog\/shared"/"@martinbechard\/wslog-shared"/g' {} \;
          
      - name: Publish shared package
        run: |
          cd shared
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish client package
        run: |
          cd client
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
